# Do not edit this file, copy this file & rename it to const.py. Any format error will result in not getting start or help message.

from pyrogram.types import InlineKeyboardMarkup, InlineKeyboardButton


#use the same format for name & user_id placeholders
START_MSG = """
Hɪ **[{}](tg://user?id={})** 🥶, I ᴀᴍ ᴀ ᴍᴇᴅɪᴀ ꜰɪɴᴅᴇʀ ʙᴏᴛ ᴡʜɪᴄʜ ꜱᴇᴀʀᴄʜ ꜰᴏʀ ꜰɪʟᴇꜱ ɪɴ ᴛᴇʟᴇɢʀᴀᴍ 😇. Jᴜꜱᴛ ꜱᴇɴᴅ qᴜᴇʀʏ ᴛᴏ ꜰɪɴᴅ ᴛʜᴇ ᴍᴇᴅɪᴀ. 🎐
Sᴇɴᴅ /help ꜰᴏʀ ᴍᴏʀᴇ ⚡."""

HELP_MSG = """
**Yᴏᴜ ᴄᴀɴ ꜰɪɴᴅ ᴛʜᴇ ʙᴏᴛ ᴄᴏᴍᴍᴀɴᴅꜱ ʜᴇʀᴇ.**
**Uꜱᴇʀ Cᴏᴍᴍᴀɴᴅꜱ:-**
/help - __Sʜᴏᴡ ᴛʜɪꜱ ʜᴇʟᴩ ᴍᴇꜱꜱᴀɢᴇ__
/settings - __Toggle settings of Precise Mode and Button Mode__
`Precise Mode:` 
- __If Enabled, bot will match the word & return results with only the exact match__
- __If Disabled, bot will match the word & return all the results containing the word__    
`Result Mode:` 
- __If Button, bot will return results in button format__
- __If List, bot will return results in list format__
- __If HyperLink, bot will return results in hyperlink format__"""


START_KB = InlineKeyboardMarkup(
    [
        [
            InlineKeyboardButton("🆘 Help", callback_data="help_cb"),
            InlineKeyboardButton(
                "👨‍💻 Source Code", url="https://github.com/EL-Coders/mediafinder"
            ),
        ]
    ]
)

HELP_KB = InlineKeyboardMarkup(
    [
        [
            InlineKeyboardButton("🔙 Back", callback_data="back_m"),
        ],
    ]
)
